In [1]:
#Cargamos librerias
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [ ]:
#Cargar archivo csv
from google.colab import files
files.upload()

In [6]:
#Cargar desde un xlsx sin indice
lastmile=pd.read_excel('lastmile_delivery_operations_mit_lift_lab.xlsx')


In [ ]:
lastmile.info(1)

In [8]:
#Identificar valores nulos
valores_nulos_lastmile=lastmile.isnull().sum()
valores_nulos_lastmile

_record_id                                         0
_title                                            10
_server_updated_at                                 0
_created_by                                        0
_updated_by                                        0
_geometry                                          0
_latitude                                          0
_longitude                                         0
arrival_of_the_freight_vehicle                     0
plates                                             1
company_if_visible                               155
visit_purpose                                      0
type_of_vehicle                                    0
number_of_operators                                0
refrigerated_truck                                 0
type_of_cargo                                      1
picture_of_the_parked_freight_vehicle              0
departure_of_the_freight_vehicle                   0
where_was_the_vehicle_parked                  

In [10]:
#Reemplazamos valores nulos con el método más sencillo
data2_lastmile=lastmile.fillna(method='bfill')

#Reemplazamos valores nulos con el método más sencillo
data2_lastmile=data2_lastmile.fillna(method='ffill')
data2_lastmile

_record_id  \
0    1e369271-598a-464c-aec7-1913e82dc2b7   
1    4a749c00-7c5f-45cf-8950-aa988a0d41b8   
2    c58a450d-fe1f-4a16-a8d8-764ebd8c49a4   
3    1a337726-bb21-4316-b3e7-f0bb4acea77e   
4    97861280-d706-46da-b345-a6dc7bc627c4   
..                                    ...   
385  f964004e-67a0-4b75-b2b0-ce04b9f0b344   
386  5656a189-19f5-45a7-b53b-1a3db0de6571   
387  bcbd462b-4c63-490b-bfec-0ef6657ead73   
388  cd9ba76d-d899-4d87-9512-486aedb1b149   
389  657541f6-7871-4165-80b2-bef59db83e18   

                                                _title  \
0    78 Avenida Orión Sur\nTlaxcalancingo Puebla 72...   
1    581 Avenida Orión Sur\nTlaxcalancingo Puebla 7...   
2    4483 Calle Camino Real a Cholula\nSan Bernardi...   
3                   Cholula de Rivadavia PUE 72768\nMX   
4                   Cholula de Rivadavia PUE 72768\nMX   
..                                                 ...   
385      406-B Avenida 2 Oriente\nPuebla PUE 72000\nMX   
386      406-B Avenida 2 Oriente\nPuebla PUE 72000\nMX   
387      406-B Avenida 2 Oriente\nPuebla PUE 72000\nMX   
388       402E Avenida 2 Oriente\nPuebla PUE 72000\nMX   
389        402 Avenida 2 Oriente\nPuebla PUE 72000\nMX   

          _server_updated_at                  _created_by  \
0    2022-11-27 22:14:32 UTC  Adriel Antonio Huerta Vidal   
1    2022-11-27 22:14:31 UTC  Adriel Antonio Huerta Vidal   
2    2022-11-27 20:12:39 UTC                María Pedraza   
3    2022-11-27 08:18:55 UTC                  Saúl Cuervo   
4    2022-11-27 08:18:54 UTC                  Saúl Cuervo   
..                       ...                          ...   
385  2022-11-03 17:54:56 UTC                 José Oropeza   
386  2022-11-03 17:54:56 UTC                 José Oropeza   
387  2022-11-03 17:54:44 UTC                 Emilio Garza   
388  2022-11-03 17:14:09 UTC                 Emilio Garza   
389  2022-11-03 17:14:09 UTC                 Emilio Garza   

                     _updated_by  \
0    Adriel Antonio Huerta Vidal   
1    Adriel Antonio Huerta Vidal   
2                  María Pedraza   
3                    Saúl Cuervo   
4                    Saúl Cuervo   
..                           ...   
385                 José Oropeza   
386                 José Oropeza   
387                 Emilio Garza   
388                 Emilio Garza   
389                 Emilio Garza   

                                         _geometry  _latitude  _longitude  \
0          SRID=4326;POINT(-98.2603919 19.0213764)  19.021376  -98.260392   
1          SRID=4326;POINT(-98.2605677 19.0211113)  19.021111  -98.260568   
2    SRID=4326;POINT(-98.2670348883 19.0352214575)  19.035221  -98.267035   
3    SRID=4326;POINT(-98.2985606801 19.0817899522)  19.081790  -98.298561   
4    SRID=4326;POINT(-98.2985890313 19.0817705579)  19.081771  -98.298589   
..                                             ...        ...         ...   
385    SRID=4326;POINT(-98.194933077 19.043612116)  19.043612  -98.194933   
386  SRID=4326;POINT(-98.1948560508 19.0436070826)  19.043607  -98.194856   
387   SRID=4326;POINT(-98.1945033093 19.043335537)  19.043336  -98.194503   
388  SRID=4326;POINT(-98.1948728731 19.0435760418)  19.043576  -98.194873   
389   SRID=4326;POINT(-98.1949010531 19.043589516)  19.043590  -98.194901   

    arrival_of_the_freight_vehicle     plates  ... used_traffic_cone  \
0                            15:35     21TFP4  ...                no   
1                            15:12     19TES7  ...                no   
2                            13:50    Sm49187  ...                no   
3                            16:46  TXK-799-A  ...                no   
4                            12:38  SN-67-573  ...                no   
..                             ...        ...  ...               ...   
385                          10:36  HL-3785-F  ...                no   
386                          10:33  SP-29-798  ...                no   
387                          11:19   05-AP-6G  ...    

In [11]:
#corroboramos valores nulos
valores_nulos=data2_lastmile.isnull().sum()
valores_nulos

_record_id                                         0
_title                                             0
_server_updated_at                                 0
_created_by                                        0
_updated_by                                        0
_geometry                                          0
_latitude                                          0
_longitude                                         0
arrival_of_the_freight_vehicle                     0
plates                                             0
company_if_visible                                 0
visit_purpose                                      0
type_of_vehicle                                    0
number_of_operators                                0
refrigerated_truck                                 0
type_of_cargo                                      0
picture_of_the_parked_freight_vehicle              0
departure_of_the_freight_vehicle                   0
where_was_the_vehicle_parked                  

In [12]:
#corroboramos valores nulos
valores_nulos=data2_lastmile.isnull().sum().sum()
valores_nulos

390

In [16]:
data2_lastmile.info(1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 30 columns):
 #   Column                                         Non-Null Count  Dtype  
---  ------                                         --------------  -----  
 0   _record_id                                     390 non-null    object 
 1   _title                                         390 non-null    object 
 2   _server_updated_at                             390 non-null    object 
 3   _created_by                                    390 non-null    object 
 4   _updated_by                                    390 non-null    object 
 5   _geometry                                      390 non-null    object 
 6   _latitude                                      390 non-null    float64
 7   _longitude                                     390 non-null    float64
 8   arrival_of_the_freight_vehicle                 390 non-null    object 
 9   plates                                         390 non

In [ ]:
data2_lastmile= data2_lastmile.drop(["describe_the_accident"],axis=1)
data2_lastmile

In [23]:
#corroboramos valores nulos
valores_nulos=data2_lastmile.isnull().sum().sum()
valores_nulos

0

In [30]:
#Filtro por columnas (Usamos solo las columnas de variables cuantitativas)
filtro_columnas_necesarias=data2_lastmile.iloc[ : , [6,7,13,22,23,28]] 
filtro_columnas_necesarias

_latitude  _longitude  number_of_operators  number_of_available_trolleys  \
0    19.021376  -98.260392                    1                             0   
1    19.021111  -98.260568                    1                             0   
2    19.035221  -98.267035                    2                             0   
3    19.081790  -98.298561                    2                             0   
4    19.081771  -98.298589                    1                             0   
..         ...         ...                  ...                           ...   
385  19.043612  -98.194933                    1                             0   
386  19.043607  -98.194856                    1                             0   
387  19.043336  -98.194503                    1                             1   
388  19.043576  -98.194873                    2                             0   
389  19.043590  -98.194901                    2                             1   

     serving_customer  maximum_number_of_vehicles_in_the_traffic_jam  
0                 1.0                                           25.0  
1                 1.0                                           25.0  
2                 1.0                                           25.0  
3                 1.0                                           25.0  
4                 1.0                                           25.0  
..                ...                                            ...  
385               1.0                                            2.0  
386               1.0                                            2.0  
387               1.0                                            2.0  
388               1.0                                            2.0  
389               1.0                                            2.0  

[390 rows x 6 columns]

In [31]:
filtro_columnas_necesarias.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 6 columns):
 #   Column                                         Non-Null Count  Dtype  
---  ------                                         --------------  -----  
 0   _latitude                                      390 non-null    float64
 1   _longitude                                     390 non-null    float64
 2   number_of_operators                            390 non-null    int64  
 3   number_of_available_trolleys                   390 non-null    int64  
 4   serving_customer                               390 non-null    float64
 5   maximum_number_of_vehicles_in_the_traffic_jam  390 non-null    float64
dtypes: float64(4), int64(2)
memory usage: 18.4 KB


In [32]:
#Método aplicando cuartiles Encuentro cuartiles de 0.25 y 0.75
y=filtro_columnas_necesarias
percentile25=y.quantile(0.25) #Q1
percentile75=y.quantile(0.75) #Q3
iqr= percentile75 - percentile25

Limite_Superior_iqr= percentile75 + 1.5*iqr
Limite_Inferior_iqr= percentile25 - 1.5*iqr
print("Limite superior permitido", Limite_Superior_iqr)
print("Limite inferior permitido", Limite_Inferior_iqr)

Limite superior permitido _latitude                                        19.101536
_longitude                                      -98.146671
number_of_operators                               3.500000
number_of_available_trolleys                      2.500000
serving_customer                                  1.000000
maximum_number_of_vehicles_in_the_traffic_jam    59.500000
dtype: float64
Limite inferior permitido _latitude                                        18.970004
_longitude                                      -98.330490
number_of_operators                              -0.500000
number_of_available_trolleys                     -1.500000
serving_customer                                  1.000000
maximum_number_of_vehicles_in_the_traffic_jam   -32.500000
dtype: float64


In [33]:
#Encontramos Outliers del dataframe 
outliers_iqr_Micro_retailer=y[(y>Limite_Superior_iqr)|(y<Limite_Inferior_iqr)]
outliers_iqr_Micro_retailer

_latitude  _longitude  number_of_operators  number_of_available_trolleys  \
0          NaN         NaN                  NaN                           NaN   
1          NaN         NaN                  NaN                           NaN   
2          NaN         NaN                  NaN                           NaN   
3          NaN         NaN                  NaN                           NaN   
4          NaN         NaN                  NaN                           NaN   
..         ...         ...                  ...                           ...   
385        NaN         NaN                  NaN                           NaN   
386        NaN         NaN                  NaN                           NaN   
387        NaN         NaN                  NaN                           NaN   
388        NaN         NaN                  NaN                           NaN   
389        NaN         NaN                  NaN                           NaN   

     serving_customer  maximum_number_of_vehicles_in_the_traffic_jam  
0                 NaN                                            NaN  
1                 NaN                                            NaN  
2                 NaN                                            NaN  
3                 NaN                                            NaN  
4                 NaN                                            NaN  
..                ...                                            ...  
385               NaN                                            NaN  
386               NaN                                            NaN  
387               NaN                                            NaN  
388               NaN                                            NaN  
389               NaN                                            NaN  

[390 rows x 6 columns]

In [35]:
#Obtenemos datos limpios del dataframe
data3_iqr_lastmile=y[(y<=Limite_Superior_iqr)&(y>=Limite_Inferior_iqr)]
data3_iqr_lastmile

_latitude  _longitude  number_of_operators  number_of_available_trolleys  \
0    19.021376  -98.260392                  1.0                           0.0   
1    19.021111  -98.260568                  1.0                           0.0   
2    19.035221  -98.267035                  2.0                           0.0   
3    19.081790  -98.298561                  2.0                           0.0   
4    19.081771  -98.298589                  1.0                           0.0   
..         ...         ...                  ...                           ...   
385  19.043612  -98.194933                  1.0                           0.0   
386  19.043607  -98.194856                  1.0                           0.0   
387  19.043336  -98.194503                  1.0                           1.0   
388  19.043576  -98.194873                  2.0                           0.0   
389  19.043590  -98.194901                  2.0                           1.0   

     serving_customer  maximum_number_of_vehicles_in_the_traffic_jam  
0                 1.0                                           25.0  
1                 1.0                                           25.0  
2                 1.0                                           25.0  
3                 1.0                                           25.0  
4                 1.0                                           25.0  
..                ...                                            ...  
385               1.0                                            2.0  
386               1.0                                            2.0  
387               1.0                                            2.0  
388               1.0                                            2.0  
389               1.0                                            2.0  

[390 rows x 6 columns]

In [36]:
#Obtenemos info de las columnas para corroborar que estemos ocupando los datos apropiados
data3_iqr_lastmile.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 390 entries, 0 to 389
Data columns (total 6 columns):
 #   Column                                         Non-Null Count  Dtype  
---  ------                                         --------------  -----  
 0   _latitude                                      390 non-null    float64
 1   _longitude                                     390 non-null    float64
 2   number_of_operators                            376 non-null    float64
 3   number_of_available_trolleys                   386 non-null    float64
 4   serving_customer                               390 non-null    float64
 5   maximum_number_of_vehicles_in_the_traffic_jam  390 non-null    float64
dtypes: float64(6)
memory usage: 18.4 KB


In [37]:
#corroboramos valores nulos
valores_nulos=y.isnull().sum()
valores_nulos

_latitude                                        0
_longitude                                       0
number_of_operators                              0
number_of_available_trolleys                     0
serving_customer                                 0
maximum_number_of_vehicles_in_the_traffic_jam    0
dtype: int64

In [38]:
#Reemplazamos valores atípicos (nulos) del dataframe con "mean"
#Realizamos una copia del dataframe
data4_iqr=y.copy()
data4_iqr=y.fillna(round(data4_iqr.mean(),1))
data4_iqr

_latitude  _longitude  number_of_operators  number_of_available_trolleys  \
0    19.021376  -98.260392                    1                             0   
1    19.021111  -98.260568                    1                             0   
2    19.035221  -98.267035                    2                             0   
3    19.081790  -98.298561                    2                             0   
4    19.081771  -98.298589                    1                             0   
..         ...         ...                  ...                           ...   
385  19.043612  -98.194933                    1                             0   
386  19.043607  -98.194856                    1                             0   
387  19.043336  -98.194503                    1                             1   
388  19.043576  -98.194873                    2                             0   
389  19.043590  -98.194901                    2                             1   

     serving_customer  maximum_number_of_vehicles_in_the_traffic_jam  
0                 1.0                                           25.0  
1                 1.0                                           25.0  
2                 1.0                                           25.0  
3                 1.0                                           25.0  
4                 1.0                                           25.0  
..                ...                                            ...  
385               1.0                                            2.0  
386               1.0                                            2.0  
387               1.0                                            2.0  
388               1.0                                            2.0  
389               1.0                                            2.0  

[390 rows x 6 columns]

In [39]:
#Observamos variables dentro del dataframe
data4_iqr

_latitude  _longitude  number_of_operators  number_of_available_trolleys  \
0    19.021376  -98.260392                    1                             0   
1    19.021111  -98.260568                    1                             0   
2    19.035221  -98.267035                    2                             0   
3    19.081790  -98.298561                    2                             0   
4    19.081771  -98.298589                    1                             0   
..         ...         ...                  ...                           ...   
385  19.043612  -98.194933                    1                             0   
386  19.043607  -98.194856                    1                             0   
387  19.043336  -98.194503                    1                             1   
388  19.043576  -98.194873                    2                             0   
389  19.043590  -98.194901                    2                             1   

     serving_customer  maximum_number_of_vehicles_in_the_traffic_jam  
0                 1.0                                           25.0  
1                 1.0                                           25.0  
2                 1.0                                           25.0  
3                 1.0                                           25.0  
4                 1.0                                           25.0  
..                ...                                            ...  
385               1.0                                            2.0  
386               1.0                                            2.0  
387               1.0                                            2.0  
388               1.0                                            2.0  
389               1.0                                            2.0  

[390 rows x 6 columns]

Hasta aqui mi parte


In [ ]:
#analizamos caso 1 de correlación entre variable de número de clientes en la tienda respecto al número de estantes en la tienda, el número de refrigeradores y el número de empleados permanentes
Vars_Indep= data4_iqr[['268_number_fridges','104_how_many_shelves_does_the_micro_retailer_have', '2_current_permanent_employees']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [ ]:
#se define modelo como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [ ]:
#Verificamos la función relacionada al modelo 
type(model)

sklearn.linear_model._base.LinearRegression

In [ ]:
#ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)

LinearRegression()

In [ ]:
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

{'fit_intercept': True,
 'normalize': 'deprecated',
 'copy_X': True,
 'n_jobs': None,
 'positive': False,
 'feature_names_in_': array(['268_number_fridges',
        '104_how_many_shelves_does_the_micro_retailer_have',
        '2_current_permanent_employees'], dtype=object),
 'n_features_in_': 3,
 'coef_': array([0.19590676, 0.0080384 , 0.08928311]),
 '_residues': 972.3842620033486,
 'rank_': 3,
 'singular_': array([260.78872511,  58.823247  ,  42.76081943]),
 'intercept_': 0.8414396869333318}

In [ ]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R determinado
model.score(Vars_Indep,Var_Dep)

0.1130725423688903

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep= data4_iqr[['268_number_fridges','104_how_many_shelves_does_the_micro_retailer_have', '2_current_permanent_employees']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [ ]:
#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
#Se escalan todos los datos
escalar= StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [ ]:
#Realizamos una predicción
y_pred= algoritmo.predict(X_test)
y_pred 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0,
       0, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

Matriz de Confusión:
[[45  1  0  0  0  0  0  0  0]
 [16  0  1  0  0  0  0  0  0]
 [16  0  2  2  0  0  0  0  0]
 [ 8  0  0  0  0  0  0  0  0]
 [ 3  0  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0  0]
 [ 0  0  0  1  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0]]


In [ ]:
#Calculo la precisión del modelo 
from sklearn.metrics import precision_score
precision= precision_score(y_test, y_pred, average="micro", pos_label="yes")
print('Precision del modelo:')
print(precision)

Precision del modelo:
0.47474747474747475


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


In [ ]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud= accuracy_score(y_test, y_pred)
print('Exactitud del modelo')
print(exactitud)

Exactitud del modelo
0.47474747474747475


In [ ]:
#Calculo la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test, y_pred, average='micro', pos_label="yes")
print('Sensibilidad del modelo')
print(sensibilidad)

Sensibilidad del modelo
0.47474747474747475


/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1375: UserWarning: Note that pos_label (set to 'yes') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,


# Conjunto de variables 2

In [ ]:
#3y4
#analizamos caso 1 de correlación entre variable de número de clientes en la tienda respecto al número de estantes en la tienda, el número de refrigeradores y el número de empleados permanentes
Vars_Indep= data4_iqr[['145_number_direct_competitors','272_card_days_receive_money', '4_number_permanent_employees_last_year']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

NameError: ignored

In [ ]:
#se define modelo como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [ ]:
#Verificamos la función relacionada al modelo 
type(model)

In [ ]:
#ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)

In [ ]:
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

In [ ]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R determinado
model.score(Vars_Indep,Var_Dep)

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep= data4_iqr[['145_number_direct_competitors','272_card_days_receive_money', '4_number_permanent_employees_last_year']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [ ]:
#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
#Se escalan todos los datos
escalar= StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

In [ ]:
#Realizamos una predicción
y_pred= algoritmo.predict(X_test)
y_pred 

In [ ]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

In [ ]:
#Calculo la precisión del modelo 
from sklearn.metrics import precision_score
precision= precision_score(y_test, y_pred, average="micro", pos_label="yes")
print('Precision del modelo:')
print(precision)

In [ ]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud= accuracy_score(y_test, y_pred)
print('Exactitud del modelo')
print(exactitud)

In [ ]:
#Calculo la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test, y_pred, average='micro', pos_label="yes")
print('Sensibilidad del modelo')
print(sensibilidad)

## CONJUNTO DE VARIABLES 3

In [ ]:
#5Y6
#analizamos caso 1 de correlación entre variable de número de clientes en la tienda respecto al número de estantes en la tienda, el número de refrigeradores y el número de empleados permanentes
Vars_Indep= data4_iqr[['36_credit_default_rate','62_frequency_only_services', '103_number_own_fridges']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [ ]:
#se define modelo como la función de regresión lineal
from sklearn.linear_model import LinearRegression
model= LinearRegression()

In [ ]:
#Verificamos la función relacionada al modelo 
type(model)

In [ ]:
#ajustamos el modelo con las variables antes declaradas
model.fit(X=Vars_Indep, y=Var_Dep)

In [ ]:
#Verificamos los coeficientes obtenidos para el modelo ajustado
model.__dict__

In [ ]:
#Evaluamos la eficiencia del modelo obtenido por medio del coeficiente R determinado
model.score(Vars_Indep,Var_Dep)

In [ ]:
#Declaramos las variables dependientes e independientes para la regresión logística
Vars_Indep= data4_iqr[['36_credit_default_rate','62_frequency_only_services', '103_number_own_fridges']]
Var_Dep= data4_iqr['97_number_of_customers_in_store']

In [ ]:
#Redefinimos las variables
X= Vars_Indep
y= Var_Dep

In [ ]:
#Dividimos el conjunto de datos en la parte de entrenamiento y prueba:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state =None)

In [ ]:
#Se escalan todos los datos
escalar= StandardScaler()

In [ ]:
#Para realizar el escalamiento de las variables "X" tanto de entrenamiento como de prueba, utilizaremos fit_transform
X_train = escalar.fit_transform(X_train)
X_test = escalar.transform(X_test)

In [ ]:
#Definimos el algoritmo a utilizar
from sklearn.linear_model import LogisticRegression
algoritmo = LogisticRegression()

In [ ]:
#Entrenamos el modelo
algoritmo.fit(X_train, y_train)

In [ ]:
#Realizamos una predicción
y_pred= algoritmo.predict(X_test)
y_pred 

In [ ]:
#Verifico la matriz de Confusión
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print('Matriz de Confusión:')
print(matriz)

In [ ]:
#Calculo la precisión del modelo 
from sklearn.metrics import precision_score
precision= precision_score(y_test, y_pred, average="micro", pos_label="yes")
print('Precision del modelo:')
print(precision)

In [ ]:
#Calculo la exactitud del modelo
from sklearn.metrics import accuracy_score
exactitud= accuracy_score(y_test, y_pred)
print('Exactitud del modelo')
print(exactitud)

In [ ]:
#Calculo la sensibilidad del modelo 
from sklearn.metrics import recall_score
sensibilidad=recall_score(y_test, y_pred, average='micro', pos_label="yes")
print('Sensibilidad del modelo')
print(sensibilidad)